Não ter descrição curta, se não tiver
ecomplus/app-bling-erp pull request #19
Opened 2021-03-02 22:32 UTC by matheusgnreis

Vi em alguns logs dando erro com slice e único lugar no parse era isso, então ajustando, pois está impedindo de importar aparentemente

2021-03-03 16:40 UTC, matheusgnreis commented
@leomp12

2021-03-03 16:47 UTC, leomp12 requested changes
Qual erro exatamente você viu? Se der pra colar o stack aqui...
De qualquer forma essa alteração não vai resolver absolutamente nada haha

Ele continuaria tentando o `slice` e portanto continuaria dando esse tal erro, a única possibilidade que eu enxerguei de um fatal aí por causa do `slice` seria se `blingProduct.descricaoComplementar` definido, não nulo e não vazio, mas não string, um número, objeto ou array, se realmente o erro for aí (cagada de tipagem do Bling) a alteração teria que ser na condição para algo como:

```js
if (blingProduct.descricaoComplementar && typeof blingProduct.descricaoComplementar === 'string') {
  // ...
}
```

2021-03-03 17:37 UTC, matheusgnreis commented
TypeError: Cannot read property 'slice' of null 
Quando é vazio, definem a propriedade como null. Problema que não é o `blingProduct.descricaoComplementar` e sim o `blingProduct.descricaoCurta`

O produto tem `blingProduct.descricaoComplementar`, mas não tem `blingProduct.descricaoCurta`

Não pretenderia colocar um if ali, a ideia era se a primeira opção nao funcionasse, colocaria um undefined ali, até testei no navegador e campo ficou com undefined. Então nem é pra ver sempre o `blingProduct.descricaoComplementar` em si

2021-03-03 17:48 UTC, leomp12 commented
@matheusgnreis não reparei a mudança aí do `descricaoComplementar` pra `descricaoCurta`, mas de qualquer forma, sua alteração não previne o erro, teria que colocar um if sim.

De qualquer forma ele entraria na condição e bateria `String(blingProduct.descricaoCurta.slice(0, 255))`, se `blingProduct.descricaoCurta` for null vai dar exatamente o mesmo erro, não sei o que testou mas o cenário que você tá dizendo é:

```js
const blingProduct = {
  descricaoComplementar: 'abc',
  descricaoCurta: null
}
const product = {}
if (blingProduct.descricaoComplementar) {
  product.short_description = String(blingProduct.descricaoCurta.slice(0, 255)) || undefined
  product.body_html = String(blingProduct.descricaoComplementar)
}
```

Precisa nem testar, com certeza absoluta vai continuar dando o mesmo pau :smile:

2021-03-03 17:50 UTC, leomp12 commented
Provavelmente eu considerei que essa `descricaoCurta` nunca seria null, se pode ser que tem que adicionar uns ifs por aí.

2021-03-04 11:50 UTC, matheusgnreis commented
No exemplo da documentação vem vazio, mas ao fazer o GET, vem como null. Coloquei uns ifs

2021-03-04 14:17 UTC, leomp12 commented
@matheusgnreis pois é, provavelmente por causa desse exemplo da documentação eu considerei que sempre seria uma string, mesmo que vazia.
Mas se fosse uma string vazia não daria o erro lá e não precisaria de alteração nenhuma, iria passar com o `short_description` vazio...

2021-03-04 14:21 UTC, leomp12 commented on functions/lib/integration/parsers/product-to-ecomplus.js
>    } else {
```suggestion
  } else if (blingProduct.descricaoCurta) {
```

Agora não daria erro, só pra evitar o `product.body_html = 'undefined'` ou `product.body_html = 'null'`.

2021-03-04 14:21 UTC, leomp12 approved these changes
valeu @matheusgnreis :+1:

2021-03-04 14:22 UTC, merged