docs(description): configuration tutorial included
ecomplus/app-bling-erp pull request #2
Opened 2020-12-07 18:12 UTC by ThaisChaves

@leomp12 , tudo bem?

Da uma olhada se era isso que precisava ou se é pra colocar em outro arquivo ou diretório. 
Abraço!

2020-12-07 23:38 UTC, leomp12 requested changes
Oi @ThaisChaves ,
Na verdade acho que não era bem isso não haha

Você chegou a falar até como cadastrar produto com variação no Bling e sinceramente isso não é necessário aqui, faz parte do manual deles, do painel deles e não da E-Com.

Também não é necessário explicar como as propriedades de produtos são mapeadas, talvez seria útil (embora não necessário) mencionar quais status adicionais de pedidos podem ser criados no Bling que seriam usados na integração. 

Em vez disso o tutorial deveria mostrar como criar a loja no Bling e salvar o código no aplicativo da E-Com Plus (não somente o token), não encontrei isso.

> Lembre que E-**C**om Plus tem o _C_ maiusculo.

2020-12-09 13:16 UTC, ThaisChaves commented on functions/public/description.md
> +Os campos sincronizados devem ser corrigidos/modificados apenas no Bling. Caso você corrija/modifique alguma destas informações no painel de controle da E-Com Plus, estas informações serão sobrescrit
Blz! Vou alterar isso aqui!!!  :+1:

2020-12-10 18:27 UTC, leomp12 approved these changes
Valeu @ThaisChaves

2020-12-10 18:27 UTC, merged

2020-12-10 19:00 UTC, leomp12 commented
@ThaisChaves eu dei um merge até pra eu conseguir visualizar as imagens mais fácil, mas na documentação ainda ficou sem falar do "Código da loja no Bling", acho que isto é importante.
A parte sobre status de pedido acho que está errada (ou só incompleta) e a instrução que consta sobre reserva de estoque não sei se é válida, acho que isto vai depender da operação da loja no ERP, não tem ligação específica com a integração.