Mudar o status para 'invoice_issued'
ecomplus/app-bling-erp pull request #3
Opened 2020-12-08 14:17 UTC by matheusgnreis

Eu sei que existe um parse apenas para status, mas seria interessante, quando entrar o invoice, o status do pedido mudar para invoice issued.
Sugestão comunidade

2020-12-08 17:05 UTC, leomp12 requested changes
Entendo a sugestão, mas tem uns problemas implementando dessa forma:

- De fato, como existe um parse para status, não é aí que isso deveria ser aplicado;
- Você não checa `partialOrder.fulfillment_status`, isso pode dar erro de sintaxe;
- O status é adicionado no histório (com data), não diretamente na shipping line;
- Eventualmente o pedido pode já ter sido enviado nesse ponto, não foi checado;

> O pedido atualmente é alterado para `invoice_issued` quando a situação no Bling é `faturado`, se for o caso podemos adicionar outras variações pra essa situação no parse de status.

2020-12-08 20:24 UTC, matheusgnreis commented
- Eventualmente o pedido pode já ter sido enviado nesse ponto, não foi checado
Problema disso é que quando no bling você emite a nota fiscal, ele muda o status automático para Atendido e ai na plataforma já vai pra enviado, então normalmente o pedido já deve estar como enviado, quando a nota fiscal entrar

2020-12-08 20:59 UTC, leomp12 commented
@matheusgnreis uai então possivelmente o mapeamento de status que não está certo, talvez esse "Atendido" deva ser só `invoice_issued`, nesse caso devemos alterar os parses de status

2020-12-09 22:04 UTC, matheusgnreis commented
Acredito que seja a melhor solução, porque segundo a imagem da anymarket que refere-se a integração deles em relação ao Bling
![anymarket](https://user-images.githubusercontent.com/35343551/101686939-84807700-3a48-11eb-9804-bab638da03d0.png)
Atendido primeiro é faturado e depois é enviado, então dá pra colocar faturado como `invoice_issued` e deixar um genérico `enviado` para ser `shipped`, porque podem criar novas situações e deixamos assim em nosso manual, quem quiser, cria mais status, quem não quiser, fica assim mesmo

2020-12-10 16:28 UTC, closed without merging